### PR TITLE
Fixing all problems with infra in develop branch.

### PR DESCRIPTION
**Pull request by 4tikhonov**

### CODE REVIEW

**Comment by antonpolishko** [comment]
Next distributives don't pass checks (using `make menuconfig`): 
- [ ] **clariah** wrong Makefile 
- [ ] **covid19museum**  wrong Makefile
- [ ] **timemachine** wrong Makefile

related to `dataverse-5.3`

**Comment by antonpolishko** [comment]
Looks like the issue is missing file that those distributives linked to
`dataverse-5.3.yaml -> ../../services-available/dataverse/dataverse-5.3.yaml`

**Comment by antonpolishko** [comment]
another missing file
- [ ] `distributives/analytics/superset-http.yaml -> ../../services-available/bi/superset-http.yaml`

**Review by ramok — COMMENTED** [review]
GmbH :)
And probably indent your name with others

**Comment by 4tikhonov** [comment]
In FAIR we trust, come and join us! :)

**Review by antonpolishko — APPROVED** [review]
Everything looks good

**Pull request merged**
